ILLEGAL     =   "ILLEGAL"
EOF         =   "EOF"

IDENT       =   "IDENT"
INT         =   "INT"

ASSIGN      =   "="
PLUS        =   "+"

COMMA       =   ","
SEMICOLON   =   ";"
COLON       =   ":"

LPAREN      =   "("
RPAREN      =   ")"
LBRACE      =   "{"
RBRACE      =   "}"
LBRACKET    =   "["
RBRACKET    =   "]"

FUNCTION    =   "FUNCTION"
LET         =   "LET"
TRUE        =   "TRUE"
FALSE       =   "FALSE"
IF          =   "IF"
ELSE        =   "ELSE"
RETURN      =   "RETURN"
WHILE       =   "WHILE"
BREAK       =   "BREAK"
CONTINUE    =   "CONTINUE"
FOR         =   "FOR"

ASSIGN      =   "="
PLUS        =   "+"
MINUS       =   "-"
BANG        =   "!"
ASTERISK    =   "*"
SLASH       =   "/"
MODULUS     =   "%"

LT          =   "<"
GT          =   ">"
LTE         =   "<="
GTE         =   ">="
EQ          =   "=="
NOT_EQ      =   "!="
AND         =   "&&"
OR         =    "||"

STRING      =   "STRING"